services:
  - type: web
    name: gecode-api
    env: go
    region: oregon
    plan: free
    buildCommand: "go build -tags netgo -ldflags '-s -w' -o app main.go"
    startCommand: "./app"
    healthCheckPath: /health
